name: verbose_regexp
version: 1.0.0+1
author: Philipp Schiffmann <philippschiffmann93@gmail.com>
description: Simulates verbose flag behavior for regular expressions in Dart.
homepage: https://github.com/pschiffmann/verbose-regexp.dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: '^1.0.0'
